# Generated by Django 2.1.7 on 2019-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
